[Setup]
Data = "cifar10"
Architecture = "BaseTest"
Epochs = 100

[Trainer]
MixedPrecision = true
MixUp = true
LabelSmoothing = false
EarlyStopping = false
LRScheduler = false
LRFinder = false
LRFinderCycles = 5
LRFinderPlot = false

[Optimizer]
Type = "SGD"
LearnRate = 0.001
Momentum = 0.9
WeightDecay = 5e-4
SGDNesterov = true
AdamAMSGrad = true
AdaGradLRDecay = 1e-4

[DataLoader]
BatchSize = 512

[Misc]
cudnnEnabled = true
cudnnBenchmark = true
CELU_alpha = 0.075  # 0.3
FC_Scale = 0.125  # 0.5,0.125
GhostBatchNorm = true
UseCELU = true
WhiteningBlock = true
StrideToPooling = true
Depthwise = true
ConvolutionBias = false
TwoConvsPerBlock = false
PoolBeforeBN = true

