[Setup]
Data = "cifar10"
Architecture = "ResNet34"
Epochs = 70

[Trainer]
MixedPrecision = true

[Optimizer]
Type = "SGD"
LearnRate = 0.01
Momentum = 0.9
WeightDecay = 5e-4
SGDNesterov = true
AdamAMSGrad = true
AdaGradLRDecay = 1e-4

[DataLoader]
BatchSize = 128

[Misc]
cudnnEnabled = true
cudnnBenchmark = true
CELU_alpha = 0.3  # 0.3
FC_Scale = 0.5  # 0.5,0.125
GhostBatchNorm = true
UseCELU = true
WhiteningBlock = true
StrideToPooling = false
Depthwise = false
ConvolutionBias = false
TwoConvsPerBlock = true
PoolBeforeBN = false

