Version = 1.0

[Setup]
Data = "cifar10"
Architecture = "BaseTest"
Epochs = 1

[Optimizer]
Type = "SDG"
LearnRate = 0.001
Momentum = 0.9
WeightDecay = 0
SDGNesterov = true
AdamAMSGrad = false
AdaGradLRDecay = 0
